import React,{useEffect,useMemo,useState} from "react";
import {api} from "./api";

const cats={all:["all"],mobiles:["smartphones","feature-phones","mobile-accessories"],electronics:["laptops","audio","televisions","smartwatches","cameras"],fashion:["mens-fashion","womens-fashion","kids-fashion"],footwear:["sports-shoes","casual-shoes","sandals"],home:["kitchen","home-decor","appliances"],beauty:["skincare","makeup","hair-care"],groceries:["staples","snacks","beverages"]};
const labels={mobiles:"Mobiles",electronics:"Electronics",fashion:"Fashion",footwear:"Footwear",home:"Home & Kitchen",beauty:"Beauty",groceries:"Groceries"};

export default function App(){
 const [products,setProducts]=useState([]),[category,setCategory]=useState("all"),[sub,setSub]=useState(""),[search,setSearch]=useState(""),[sort,setSort]=useState("featured"),[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem("hg_cart")||"[]")),[user,setUser]=useState(null),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[msg,setMsg]=useState(""),[wishlist,setWishlist]=useState(()=>JSON.parse(localStorage.getItem("hg_wish")||"[]"));
 const load=async()=>{try{const q=new URLSearchParams({category,subcategory:sub,search});let p=await api("/products?"+q);if(sort==="priceLow")p.sort((a,b)=>a.price-b.price);if(sort==="priceHigh")p.sort((a,b)=>b.price-a.price);if(sort==="rating")p.sort((a,b)=>b.rating-a.rating);setProducts(p)}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[category,sub,sort]); useEffect(()=>{let t=setTimeout(load,250);return()=>clearTimeout(t)},[search]); useEffect(()=>{localStorage.setItem("hg_cart",JSON.stringify(cart))},[cart]);useEffect(()=>{localStorage.setItem("hg_wish",JSON.stringify(wishlist))},[wishlist]);
 useEffect(()=>{api("/me").then(x=>x.loggedIn&&setUser(x)).catch(()=>{})},[]);
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.price*x.qty,0),[cart]),count=cart.reduce((s,x)=>s+x.qty,0);
 const add=p=>{setCart(c=>{let f=c.find(x=>x.id===p.id);return f?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setMsg("Added to cart ✓")};
 const change=(id,n)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(0,n)}:x).filter(x=>x.qty));
 const login=async(e,p)=>{let d=await api("/login",{method:"POST",body:JSON.stringify({email:e,password:p})});setUser(d.user);setModal(null);setMsg("Welcome, "+d.user.name)};
 const register=async(n,e,p)=>{await api("/register",{method:"POST",body:JSON.stringify({name:n,email:e,password:p})});await login(e,p)};
 const logout=async()=>{await api("/logout",{method:"POST"});setUser(null);setMsg("Logged out")};
 const toggleWish=id=>setWishlist(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
 return <div>
  <div className="top">🚚 Free delivery on orders above ₹499 &nbsp; | &nbsp; Easy returns &nbsp; | &nbsp; Secure checkout</div>
  <nav><div className="logo" onClick={()=>{setCategory("all");setSub("");window.scrollTo({top:0,behavior:"smooth"})}}>HarGhar<span>Shop</span></div>
   <div className="searchbox"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products, brands and categories..."/></div>
   <div className="actions">{user?<><button className="plain" onClick={()=>setModal("orders")}>👤 {user.name}</button>{user.role==="admin"&&<button className="plain" onClick={()=>setModal("admin")}>Admin</button>}<button className="plain" onClick={logout}>Logout</button></>:<button className="plain" onClick={()=>setModal("login")}>Login / Sign Up</button>}<button className="cartbtn" onClick={()=>setModal("cart")}>🛒 Cart <b>{count}</b></button></div>
  </nav>
  <div className="cats"><button className={category==="all"?"active":""} onClick={()=>{setCategory("all");setSub("")}}>All</button>{Object.keys(labels).map(c=><button className={category===c?"active":""} onClick={()=>{setCategory(c);setSub("")}} key={c}>{labels[c]}</button>)}</div>
  <section className="hero"><div><span className="pill">BIG SAVING DAYS</span><h1>Everything you need,<br/><em>right at your doorstep.</em></h1><p>Shop mobiles, electronics, fashion, footwear, home, beauty & groceries.</p><button onClick={()=>document.getElementById("products").scrollIntoView({behavior:"smooth"})}>Shop Now →</button></div><div className="heroOffer"><small>UP TO</small><strong>70%</strong><small>OFF</small></div></section>
  <div className="trust"><span>🚚 <b>Fast Delivery</b><small>Across India</small></span><span>↩️ <b>Easy Returns</b><small>Hassle-free returns</small></span><span>🔒 <b>Secure Payments</b><small>100% protected</small></span><span>⭐ <b>Top Rated</b><small>Quality products</small></span></div>
  <main id="products"><div className="head"><div><h2>{category==="all"?"Trending Products":labels[category]}</h2><p>{products.length} products available</p></div><div className="filters">{category!=="all"&&<select value={sub} onChange={e=>setSub(e.target.value)}><option value="">All {labels[category]}</option>{cats[category].filter(x=>x!=="all").map(x=><option key={x}>{x.replaceAll("-"," ")}</option>)}</select>}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Sort: Featured</option><option value="priceLow">Price: Low to High</option><option value="priceHigh">Price: High to Low</option><option value="rating">Top Rated</option></select></div></div>
   {products.length?<div className="grid">{products.map(p=><article className="card" key={p.id} onClick={()=>setSelected(p)}><button className={"wish "+(wishlist.includes(p.id)?"liked":"")} onClick={e=>{e.stopPropagation();toggleWish(p.id)}}>♡</button><div className="photo"><img src={p.image} alt={p.name}/></div><span className="rating">★ {p.rating}</span><h3>{p.name}</h3><small className="muted">{p.subcategory.replaceAll("-"," ")}</small><div className="price"><b>₹{p.price.toLocaleString("en-IN")}</b> <del>₹{p.old_price.toLocaleString("en-IN")}</del></div><div className="discount">{Math.round((1-p.price/p.old_price)*100)}% off</div><button className="add" onClick={e=>{e.stopPropagation();add(p)}}>Add to Cart</button></article>)}</div>:<div className="empty">No products found. Try another search.</div>}
  </main>
  <footer><div><h2>HarGhar<span>Shop</span></h2><p>India's everyday online shopping destination.</p></div><div><b>Shop</b><p>Mobiles · Electronics · Fashion · Home · Beauty · Groceries</p></div><div><b>Customer Care</b><p>Help Center · Returns · Orders · Secure Payments</p></div><div><b>© 2026 HarGharShop</b><p>Founder & Developer: Sumit Adhav</p></div></footer>
  {msg&&<div className="toast" onClick={()=>setMsg("")}>{msg}</div>}
  {modal==="login"&&<Auth mode="login" close={()=>setModal(null)} onLogin={login} onRegister={register}/>}
  {modal==="cart"&&<Cart cart={cart} change={change} total={total} close={()=>setModal(null)} checkout={()=>{if(!user){setModal("login")}else setModal("checkout")}}/>}
  {modal==="checkout"&&<Checkout user={user} cart={cart} total={total} close={()=>setModal(null)} done={(id)=>{setCart([]);setModal(null);setMsg("Order #"+id+" placed successfully 🎉")}}/>}
  {modal==="orders"&&<Orders close={()=>setModal(null)}/>}
  {modal==="admin"&&user?.role==="admin"&&<Admin close={()=>setModal(null)} refresh={load}/>}
  {selected&&<ProductModal p={selected} add={add} close={()=>setSelected(null)} />}
 </div>
}

function Overlay({children,close,wide=false}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={"modal "+(wide?"wide":"")}><button className="x" onClick={close}>×</button>{children}</div></div>}
function Auth({mode,close,onLogin,onRegister}){const [signup,setSignup]=useState(mode==="register"),[n,setN]=useState(""),[e,setE]=useState("admin@hargharshop.com"),[p,setP]=useState("Admin@12345"),[err,setErr]=useState("");const submit=async()=>{try{signup?await onRegister(n,e,p):await onLogin(e,p)}catch(x){setErr(x.message)}};return <Overlay close={close}><div className="auth"><h2>{signup?"Create account":"Welcome back"}</h2>{signup&&<input value={n} onChange={x=>setN(x.target.value)} placeholder="Full name"/>}<input value={e} onChange={x=>setE(x.target.value)} placeholder="Email address"/><input type="password" value={p} onChange={x=>setP(x.target.value)} placeholder="Password (6+ characters)"/>{err&&<p className="error">{err}</p>}<button className="primary full" onClick={submit}>{signup?"Create Account":"Login"}</button><p className="switch">{signup?"Already have an account?":"New to HarGharShop?"} <button onClick={()=>setSignup(!signup)}>{signup?"Login":"Create account"}</button></p>{!signup&&<small className="demo">Admin demo: admin@hargharshop.com / Admin@12345</small>}</div></Overlay>}
function Cart({cart,change,total,close,checkout}){return <Overlay close={close}><h2>Your Cart <span className="muted">({cart.reduce((s,x)=>s+x.qty,0)} items)</span></h2>{cart.length?<><div className="cartlist">{cart.map(x=><div className="cartitem" key={x.id}><img src={x.image}/><div><b>{x.name}</b><p>₹{x.price.toLocaleString("en-IN")}</p><div className="qty"><button onClick={()=>change(x.id,x.qty-1)}>−</button><span>{x.qty}</span><button onClick={()=>change(x.id,x.qty+1)}>+</button></div></div><strong>₹{(x.price*x.qty).toLocaleString("en-IN")}</strong></div>)}</div><div className="total"><span>Total</span><b>₹{total.toLocaleString("en-IN")}</b></div><button className="primary full" onClick={checkout}>Proceed to Checkout</button></>:<div className="empty">🛒<br/><b>Your cart is empty</b><p>Add something you love!</p></div>}</Overlay>}
function Checkout({user,cart,total,close,done}){const [f,setF]=useState({name:user?.name||"",mobile:"",address:"",payment:"COD"}),[err,setErr]=useState("");const ch=e=>setF({...f,[e.target.name]:e.target.value});const submit=async()=>{try{let d=await api("/orders",{method:"POST",body:JSON.stringify({...f,customer_name:f.name,total,items:cart})});done(d.orderId)}catch(e){setErr(e.message)}};return <Overlay close={close} wide><h2>Checkout</h2><div className="checkoutgrid"><div><label>Full name<input name="name" value={f.name} onChange={ch}/></label><label>Mobile number<input name="mobile" maxLength="10" value={f.mobile} onChange={ch} placeholder="10 digit mobile"/></label><label>Delivery address<textarea name="address" value={f.address} onChange={ch} rows="4" placeholder="House no, street, city, PIN"/></label><label>Payment<select name="payment" value={f.payment} onChange={ch}><option>COD</option><option>UPI</option><option>Card</option></select></label>{err&&<p className="error">{err}</p>}</div><div className="summary"><h3>Order Summary</h3>{cart.map(x=><p key={x.id}>{x.name} × {x.qty}<b>₹{(x.price*x.qty).toLocaleString("en-IN")}</b></p>)}<hr/><h3>Total <b>₹{total.toLocaleString("en-IN")}</b></h3><button className="primary full" onClick={submit}>Place Order</button></div></div></Overlay>}
function Orders({close}){const [orders,setOrders]=useState([]);useEffect(()=>{api("/orders").then(setOrders).catch(()=>{})},[]);return <Overlay close={close} wide><h2>My Orders</h2>{orders.length?orders.map(o=><div className="order" key={o.id}><div><b>Order #{o.id}</b><span className="status">{o.status}</span><small>{o.payment} · ₹{o.total.toLocaleString("en-IN")}</small></div><div>{o.items.map(i=><small key={i.id}>{i.name} × {i.qty}<br/></small>)}</div></div>):<div className="empty">No orders yet.</div>}</Overlay>}
function ProductModal({p,add,close}){return <Overlay close={close} wide><div className="productdetail"><img src={p.image}/><div><span className="rating">★ {p.rating}</span><h2>{p.name}</h2><p className="muted">{p.subcategory.replaceAll("-"," ")}</p><h1>₹{p.price.toLocaleString("en-IN")} <del>₹{p.old_price.toLocaleString("en-IN")}</del></h1><p>{p.description}</p><p className="green">✓ {p.stock} available in stock</p><button className="primary" onClick={()=>{add(p);close()}}>Add to Cart</button></div></div></Overlay>}
function Admin({close,refresh}){const [f,setF]=useState({name:"",category:"mobiles",subcategory:"smartphones",price:"",old_price:"",rating:"4.5",stock:"10",image:"",description:""}),[orders,setOrders]=useState([]);const ch=e=>setF({...f,[e.target.name]:e.target.value});const add=async()=>{try{await api("/admin/products",{method:"POST",body:JSON.stringify(f)});alert("Product added");setF({...f,name:"",price:"",old_price:"",image:"",description:""});refresh()}catch(e){alert(e.message)}};const load=async()=>setOrders(await api("/admin/orders"));const status=async(id,s)=>{await api("/admin/orders/"+id,{method:"PUT",body:JSON.stringify({status:s})});load()};return <Overlay close={close} wide><h2>Admin Dashboard</h2><div className="form">{Object.keys(f).map(k=><input key={k} name={k} value={f[k]} onChange={ch} placeholder={k.replace("_"," ")}/>)}</div><button className="primary" onClick={add}>Add Product</button> <button className="secondary" onClick={load}>Load Orders</button><div className="adminorders">{orders.map(o=><div className="order" key={o.id}><b>#{o.id} · {o.customer_name}</b><span>₹{o.total}</span><select value={o.status} onChange={e=>status(o.id,e.target.value)}>{["Placed","Packed","Shipped","Delivered","Cancelled"].map(s=><option key={s}>{s}</option>)}</select></div>)}</div></Overlay>}
